version: 2
updates:
  # Monitor NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/onto-editor/eidos"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "benjaminhoffman"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group non-security updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Monitor test project dependencies
  - package-ecosystem: "nuget"
    directory: "/onto-editor/Eidos.Tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "tests"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci-cd"
