// <auto-generated />
using System;
using Eidos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eidos.Migrations
{
    [DbContext(typeof(OntologyDbContext))]
    [Migration("20251108221832_AddMergeRequestApprovalWorkflow")]
    partial class AddMergeRequestApprovalWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Eidos.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Eidos.Models.CollaborationPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollaborationProjectGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBumpedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LookingFor")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeCommitment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationProjectGroupId");

                    b.HasIndex("Domain")
                        .HasDatabaseName("IX_CollaborationPost_Domain");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CollaborationPost_IsActive");

                    b.HasIndex("OntologyId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CollaborationPost_UserId");

                    b.HasIndex("IsActive", "CreatedAt")
                        .HasDatabaseName("IX_CollaborationPost_IsActive_CreatedAt");

                    b.ToTable("CollaborationPosts");
                });

            modelBuilder.Entity("Eidos.Models.CollaborationResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollaborationPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationPostId")
                        .HasDatabaseName("IX_CollaborationResponse_PostId");

                    b.HasIndex("UserId", "CollaborationPostId")
                        .HasDatabaseName("IX_CollaborationResponse_UserId_PostId");

                    b.ToTable("CollaborationResponses");
                });

            modelBuilder.Entity("Eidos.Models.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Examples")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<string>("SimpleExplanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOntology")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OntologyId")
                        .HasDatabaseName("IX_Concept_OntologyId");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Eidos.Models.ConceptProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFunctional")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RangeConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("IX_ConceptProperty_ConceptId");

                    b.HasIndex("RangeConceptId");

                    b.ToTable("ConceptProperties");
                });

            modelBuilder.Entity("Eidos.Models.ConceptRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AllowedConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxCardinality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinCardinality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RestrictionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllowedConceptId");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("IX_ConceptRestriction_ConceptId");

                    b.ToTable("ConceptRestrictions");
                });

            modelBuilder.Entity("Eidos.Models.CustomConceptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Examples")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OntologyId");

                    b.ToTable("CustomConceptTemplates");
                });

            modelBuilder.Entity("Eidos.Models.FeatureToggle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureToggles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "User Management",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Display additional test users in the user selector for MVP testing",
                            IsEnabled = true,
                            Key = "show-test-users",
                            Name = "Show Test Users",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Collaboration",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allow multiple users to collaborate on the same ontology",
                            IsEnabled = false,
                            Key = "enable-collaboration",
                            Name = "Enable Collaboration (Future)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Collaboration",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sync changes across users in real-time using SignalR",
                            IsEnabled = false,
                            Key = "enable-real-time-sync",
                            Name = "Enable Real-time Sync (Future)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Eidos.Models.GuestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyShareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OntologyShareId")
                        .HasDatabaseName("IX_GuestSession_OntologyShareId");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("GuestSessions");
                });

            modelBuilder.Entity("Eidos.Models.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("OntologyId")
                        .HasDatabaseName("IX_Individual_OntologyId");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("Eidos.Models.IndividualProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConceptPropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndividualId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("IndividualProperties");
                });

            modelBuilder.Entity("Eidos.Models.IndividualRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OntologyUri")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceIndividualId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetIndividualId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OntologyId");

                    b.HasIndex("SourceIndividualId");

                    b.HasIndex("TargetIndividualId");

                    b.ToTable("IndividualRelationships");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedReviewerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConceptsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptsModified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasConflicts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndividualsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndividualsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndividualsModified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipsModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewComments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedReviewerUserId")
                        .HasDatabaseName("IX_MergeRequest_AssignedReviewerUserId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_MergeRequest_CreatedByUserId");

                    b.HasIndex("OntologyId")
                        .HasDatabaseName("IX_MergeRequest_OntologyId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("OntologyId", "Status")
                        .HasDatabaseName("IX_MergeRequest_OntologyId_Status");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequestChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MergeRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MergeRequestId")
                        .HasDatabaseName("IX_MergeRequestChange_MergeRequestId");

                    b.ToTable("MergeRequestChanges");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequestComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemComment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MergeRequestChangeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MergeRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MergeRequestChangeId");

                    b.HasIndex("MergeRequestId")
                        .HasDatabaseName("IX_MergeRequestComment_MergeRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("MergeRequestId", "CreatedAt")
                        .HasDatabaseName("IX_MergeRequestComment_MergeRequestId_CreatedAt");

                    b.ToTable("MergeRequestComments");
                });

            modelBuilder.Entity("Eidos.Models.Ontology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPublicEdit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConceptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespacePrefixes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentOntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvenanceNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvenanceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RelationshipCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesBFO")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesProvO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentOntologyId");

                    b.HasIndex("UserId");

                    b.ToTable("Ontologies");
                });

            modelBuilder.Entity("Eidos.Models.OntologyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestSessionToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_OntologyActivity_UserId");

                    b.HasIndex("OntologyId", "CreatedAt")
                        .HasDatabaseName("IX_OntologyActivity_OntologyId_CreatedAt");

                    b.HasIndex("OntologyId", "VersionNumber")
                        .HasDatabaseName("IX_OntologyActivity_OntologyId_VersionNumber");

                    b.ToTable("OntologyActivities");
                });

            modelBuilder.Entity("Eidos.Models.OntologyGroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("OntologyId", "UserGroupId")
                        .IsUnique()
                        .HasDatabaseName("IX_OntologyGroupPermission_OntologyId_GroupId");

                    b.ToTable("OntologyGroupPermissions");
                });

            modelBuilder.Entity("Eidos.Models.OntologyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConceptsImported")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedConceptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedOntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<string>("Prefix")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UpdateAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedOntologyId");

                    b.HasIndex("OntologyId");

                    b.HasIndex("OntologyId", "LinkType");

                    b.ToTable("OntologyLinks", t =>
                        {
                            t.HasCheckConstraint("CK_OntologyLink_HasTarget", "(LinkType = 0 AND Uri IS NOT NULL) OR (LinkType = 1 AND LinkedOntologyId IS NOT NULL)");

                            t.HasCheckConstraint("CK_OntologyLink_NoSelfReference", "OntologyId <> LinkedOntologyId OR LinkedOntologyId IS NULL");
                        });
                });

            modelBuilder.Entity("Eidos.Models.OntologyShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowGuestAccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OntologyId")
                        .HasDatabaseName("IX_OntologyShare_OntologyId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.ToTable("OntologyShares");
                });

            modelBuilder.Entity("Eidos.Models.OntologyTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_OntologyTag_Tag");

                    b.HasIndex("OntologyId", "Tag")
                        .HasDatabaseName("IX_OntologyTag_OntologyId_Tag");

                    b.ToTable("OntologyTags");
                });

            modelBuilder.Entity("Eidos.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Eidos.Models.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OntologyUri")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Strength")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetConceptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OntologyId")
                        .HasDatabaseName("IX_Relationship_OntologyId");

                    b.HasIndex("SourceConceptId");

                    b.HasIndex("TargetConceptId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Eidos.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Eidos.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Eidos.Models.UserGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroupAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserGroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserGroupMember_GroupId_UserId");

                    b.ToTable("UserGroupMembers");
                });

            modelBuilder.Entity("Eidos.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoColorByCategory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultConceptColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultEdgeThickness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultNodeSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultRelationshipColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HasPartRelationshipColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InformationColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IsARelationshipColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartOfRelationshipColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedToRelationshipColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowEdgeLabels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowKeyboardShortcuts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextSizeScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Eidos.Models.UserShareAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OntologyShareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OntologyShareId")
                        .HasDatabaseName("IX_UserShareAccess_OntologyShareId");

                    b.HasIndex("UserId", "OntologyShareId")
                        .IsUnique();

                    b.ToTable("UserShareAccesses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eidos.Models.CollaborationPost", b =>
                {
                    b.HasOne("Eidos.Models.UserGroup", "CollaborationProjectGroup")
                        .WithMany()
                        .HasForeignKey("CollaborationProjectGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany()
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollaborationProjectGroup");

                    b.Navigation("Ontology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eidos.Models.CollaborationResponse", b =>
                {
                    b.HasOne("Eidos.Models.CollaborationPost", "CollaborationPost")
                        .WithMany("Responses")
                        .HasForeignKey("CollaborationPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollaborationPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eidos.Models.Concept", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("Concepts")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Eidos.Models.ConceptProperty", b =>
                {
                    b.HasOne("Eidos.Models.Concept", "Concept")
                        .WithMany("ConceptProperties")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Concept", "RangeConcept")
                        .WithMany()
                        .HasForeignKey("RangeConceptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Concept");

                    b.Navigation("RangeConcept");
                });

            modelBuilder.Entity("Eidos.Models.ConceptRestriction", b =>
                {
                    b.HasOne("Eidos.Models.Concept", "AllowedConcept")
                        .WithMany()
                        .HasForeignKey("AllowedConceptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eidos.Models.Concept", "Concept")
                        .WithMany("Restrictions")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowedConcept");

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("Eidos.Models.CustomConceptTemplate", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("CustomTemplates")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Eidos.Models.GuestSession", b =>
                {
                    b.HasOne("Eidos.Models.OntologyShare", "OntologyShare")
                        .WithMany("GuestSessions")
                        .HasForeignKey("OntologyShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OntologyShare");
                });

            modelBuilder.Entity("Eidos.Models.Individual", b =>
                {
                    b.HasOne("Eidos.Models.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("Individuals")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Eidos.Models.IndividualProperty", b =>
                {
                    b.HasOne("Eidos.Models.Individual", "Individual")
                        .WithMany("Properties")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("Eidos.Models.IndividualRelationship", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("IndividualRelationships")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Individual", "SourceIndividual")
                        .WithMany("RelationshipsAsSource")
                        .HasForeignKey("SourceIndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Individual", "TargetIndividual")
                        .WithMany("RelationshipsAsTarget")
                        .HasForeignKey("TargetIndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ontology");

                    b.Navigation("SourceIndividual");

                    b.Navigation("TargetIndividual");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequest", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", "AssignedReviewer")
                        .WithMany()
                        .HasForeignKey("AssignedReviewerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany()
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedReviewer");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Ontology");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequestChange", b =>
                {
                    b.HasOne("Eidos.Models.MergeRequest", "MergeRequest")
                        .WithMany("Changes")
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequestComment", b =>
                {
                    b.HasOne("Eidos.Models.MergeRequestChange", "MergeRequestChange")
                        .WithMany()
                        .HasForeignKey("MergeRequestChangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.MergeRequest", "MergeRequest")
                        .WithMany("Comments")
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("MergeRequestChange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eidos.Models.Ontology", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "ParentOntology")
                        .WithMany("ChildOntologies")
                        .HasForeignKey("ParentOntologyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany("Ontologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentOntology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eidos.Models.OntologyActivity", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany()
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ontology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eidos.Models.OntologyGroupPermission", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.UserGroup", "UserGroup")
                        .WithMany("OntologyPermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("Ontology");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Eidos.Models.OntologyLink", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "LinkedOntology")
                        .WithMany()
                        .HasForeignKey("LinkedOntologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("LinkedOntologies")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedOntology");

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Eidos.Models.OntologyShare", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany()
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Eidos.Models.OntologyTag", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("OntologyTags")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Eidos.Models.Property", b =>
                {
                    b.HasOne("Eidos.Models.Concept", "Concept")
                        .WithMany("Properties")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("Eidos.Models.Relationship", b =>
                {
                    b.HasOne("Eidos.Models.Ontology", "Ontology")
                        .WithMany("Relationships")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Concept", "SourceConcept")
                        .WithMany("RelationshipsAsSource")
                        .HasForeignKey("SourceConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eidos.Models.Concept", "TargetConcept")
                        .WithMany("RelationshipsAsTarget")
                        .HasForeignKey("TargetConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ontology");

                    b.Navigation("SourceConcept");

                    b.Navigation("TargetConcept");
                });

            modelBuilder.Entity("Eidos.Models.UserGroup", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Eidos.Models.UserGroupMember", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eidos.Models.UserGroup", "UserGroup")
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Eidos.Models.UserPreferences", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Eidos.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eidos.Models.UserShareAccess", b =>
                {
                    b.HasOne("Eidos.Models.OntologyShare", "OntologyShare")
                        .WithMany()
                        .HasForeignKey("OntologyShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OntologyShare");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eidos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Eidos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eidos.Models.ApplicationUser", b =>
                {
                    b.Navigation("Ontologies");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Eidos.Models.CollaborationPost", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Eidos.Models.Concept", b =>
                {
                    b.Navigation("ConceptProperties");

                    b.Navigation("Properties");

                    b.Navigation("RelationshipsAsSource");

                    b.Navigation("RelationshipsAsTarget");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("Eidos.Models.Individual", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("RelationshipsAsSource");

                    b.Navigation("RelationshipsAsTarget");
                });

            modelBuilder.Entity("Eidos.Models.MergeRequest", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Eidos.Models.Ontology", b =>
                {
                    b.Navigation("ChildOntologies");

                    b.Navigation("Concepts");

                    b.Navigation("CustomTemplates");

                    b.Navigation("GroupPermissions");

                    b.Navigation("IndividualRelationships");

                    b.Navigation("Individuals");

                    b.Navigation("LinkedOntologies");

                    b.Navigation("OntologyTags");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("Eidos.Models.OntologyShare", b =>
                {
                    b.Navigation("GuestSessions");
                });

            modelBuilder.Entity("Eidos.Models.UserGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("OntologyPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
